name: CI/CD Pipeline

on:
  push:
    branches: ['**'] # Запуск на любой ветке
  pull_request:
    branches: [main] # Запуск при попытке мерджа в main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Prettier check
        run: bun run prettier --check .

      - name: Lint check
        run: bun run lint

      - name: Type check
        run: bun run typecheck

      - name: Production build
        run: bun run build