/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Выход из системы (аннулирование refresh-токена) */
        post: operations["v1_auth_logout_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/auth/otp/request/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Запрос OTP-кода */
        post: operations["v1_auth_otp_request_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/auth/otp/verify/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Верификация OTP-кода */
        post: operations["v1_auth_otp_verify_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Обновление access-токена
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_token_refresh_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/checkout/subscription": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Идемпотентное создание платежа за абонемент. Заголовок X-Idempotency-Key (UUID v4) обязателен. Родитель определяется по сессии — parent_id в теле не принимается. */
        post: operations["v1_checkout_subscription_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/checkout/trial": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Идемпотентная запись на пробное занятие. Заголовок X-Idempotency-Key (UUID v4) обязателен. Не более одного пробного на ребёнка по кружку. Бесплатное пробное подтверждается сразу (CONFIRMED). */
        post: operations["v1_checkout_trial_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/bookings/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Мои записи: пробные занятия и события одной лентой
         * @description period=upcoming (по умолчанию) — ближайшие сверху; past — свежие сверху; all — сначала предстоящие, потом прошедшие. «Прошло» — по дате: сегодняшнее ещё предстоящее. Отменённые не показываются. status: PENDING — ждёт оплаты/подтверждения, CONFIRMED — записан. Уникальный ключ карточки — пара (kind, id). Без limit — весь список массивом; с ?limit=N&offset=M — конверт {count, next, previous, results}, где results — те же элементы.
         */
        get: operations["me_bookings"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/children/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Добавить ребёнка */
        post: operations["me_child_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/children/{id}/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /**
         * Удалить ребёнка (архивация)
         * @description Мягкое удаление: ребёнок пропадает из профиля и чекаута, история покупок и посещений сохраняется. 409 CHILD_HAS_ACTIVE_ENROLLMENTS, пока есть действующий абонемент, неоплаченная бронь или предстоящее пробное — список в extensions.active_enrollments.
         */
        delete: operations["me_child_delete"]
        options?: never
        head?: never
        /** Изменить данные ребёнка */
        patch: operations["me_child_update"]
        trace?: never
    }
    "/api/v1/me/deposit/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Баланс депозита родителя
         * @description Баланс в копейках. Нет депозита — 0. Нужен чекауту, чтобы решить, предлагать ли оплату с депозита (use_deposit).
         */
        get: operations["me_deposit"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/deposit/entries/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * История движений депозита
         * @description Новые сверху. amount со знаком: плюс — начисление, минус — списание. Без limit — весь список массивом; с ?limit=N&offset=M — конверт {count, next, previous, results}, где results — те же элементы.
         */
        get: operations["me_deposit_entries"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/profile/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Профиль родителя с детьми */
        get: operations["me_profile"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /** Изменить анкету родителя */
        patch: operations["me_profile_update"]
        trace?: never
    }
    "/api/v1/me/subscriptions/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Мои абонементы: действующие и история
         * @description Только оплаченные: ACTIVE (сверху) и EXPIRED, внутри — новые сверху. У истёкшего — все купленные слоты, остаток 0 (он ушёл на депозит). Без limit — весь список массивом; с ?limit=N&offset=M — конверт {count, next, previous, results}, где results — те же элементы.
         */
        get: operations["me_subscriptions"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/trials/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Пробные занятия детей родителя (устарела)
         * @deprecated
         * @description Устарела: используйте GET /me/bookings/?kind=TRIAL — там пробные вместе с событиями в одном формате. Работает, пока фронт не перейдёт. Новые по дате пробного сверху. Без limit — весь список массивом; с ?limit=N&offset=M — конверт {count, next, previous, results}, где results — те же элементы.
         */
        get: operations["me_trials"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/me/upcoming/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Лента ближайших активностей (занятия + события)
         * @description Хронологически, ближайшие сверху. Горизонт weeks (по умолчанию 4, максимум 8). Без limit — весь список массивом; с ?limit=N&offset=M — конверт {count, next, previous, results}, где results — те же элементы.
         */
        get: operations["me_upcoming"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/activities/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Полный каталог кружков («Все кружки») */
        get: operations["public_activities_list"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/activities/{id}/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Детальная карточка кружка с подгруппами */
        get: operations["public_activity_detail"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/activities/{id}/next-slots/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Свободные занятия кружка для пробного на две недели
         * @description Окно — сегодня + 13 дней. Только занятия, которые ещё не начались, не отменены и где есть свободное место; переносы уже применены. Из элемента берутся schedule_id и date для POST /checkout/trial (trial_date = date). Нет свободных занятий — пустой slots. Кэш 30 секунд.
         */
        get: operations["public_activity_next_slots"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/activities/popular/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Топ-3 популярных кружка */
        get: operations["public_activities_popular"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/callback/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Заказ обратного звонка */
        post: operations["v1_public_callback_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/events/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Афиша: будущие события и прошедшие за 7 дней */
        get: operations["public_events_list"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/events/{event_id}/register/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Гостевая регистрация на событие */
        post: operations["public_event_register"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/feedback/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Обратная связь */
        post: operations["v1_public_feedback_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/gallery/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Опубликованные фото галереи
         * @description Без query-параметров — весь список массивом (обратная совместимость). С ?limit=N (опц. &offset=M) — постраничная выдача в конверте {count, next, previous, results} для подгрузки по кнопке/скроллу.
         */
        get: operations["public_gallery_list"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/plans/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Тарифные планы абонементов */
        get: operations["public_plans_list"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/schedule/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Недельная сетка расписания */
        get: operations["public_schedule_week"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/public/teachers/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Преподаватели с их кружками */
        get: operations["public_teachers_list"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/v1/webhooks/yookassa": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Вебхук ЮКассы. Быстро ставит верификацию платежа в очередь. */
        post: operations["v1_webhooks_yookassa_create"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        ActivityCard: {
            readonly id: number
            /** Название */
            name: string
            /** Слуг */
            slug: string
            /** Категория */
            category?: string
            /** Цена */
            price?: number
            /** Обложка (URL) */
            cover_image?: string
            /** Краткое описание */
            short_description?: string
            /** Особенности */
            features?: unknown
            /** Теги */
            tags?: unknown
        }
        ActivityDetail: {
            readonly id: number
            /** Название */
            name: string
            /** Слуг */
            slug: string
            /** Категория */
            category?: string
            /** Цена */
            price?: number
            /** Обложка (URL) */
            cover_image?: string
            /** Краткое описание */
            short_description?: string
            /** Особенности */
            features?: unknown
            /** Теги */
            tags?: unknown
            /** Описание */
            description?: string
            readonly groups: components["schemas"]["ScheduleGroupPublic"][]
            readonly teachers: components["schemas"]["ActivityTeacherNested"][]
            readonly days_of_week: number[]
        }
        ActivityNested: {
            readonly id: number
            readonly name: string
            readonly slug: string
        }
        ActivityTeacherNested: {
            readonly id: number
            readonly full_name: string
            readonly photo_url: string
            readonly position: string
        }
        Booking: {
            readonly kind: components["schemas"]["KindEnum"]
            readonly id: number
            readonly title: string
            readonly group_name: string | null
            /** Format: date */
            readonly date: string
            /** Format: time */
            readonly start_time: string
            /** Format: time */
            readonly end_time: string
            /** @description Копейки. Событие — цена × участники; null — цены не из чего взять */
            readonly cost: number | null
            readonly child_name: string
            readonly student_id: number | null
            readonly attendees_count: number | null
            readonly status: components["schemas"]["BookingStatusEnum"]
            readonly status_display: string
            readonly is_past: boolean
            readonly activity_id: number | null
            readonly event_id: number | null
        }
        /**
         * @description * `PENDING` - Ожидает
         *     * `CONFIRMED` - Записан
         * @enum {string}
         */
        BookingStatusEnum: "PENDING" | "CONFIRMED"
        CallbackRequestCreateRequest: {
            /** Имя */
            name: string
            /** Телефон */
            phone: string
            /** Удобное время звонка */
            preferred_time_window: components["schemas"]["PreferredTimeWindowEnum"]
            /** @description Согласие на обработку персональных данных. Обязательно true; галочка на фронте не должна стоять по умолчанию */
            pd_consent: boolean
            /** @default  */
            website_url: string
            /** @default  */
            captcha_token: string
        }
        CapacityNested: {
            readonly max: number
            readonly taken: number
            readonly free: number
        }
        CheckoutResponse: {
            /** Format: uuid */
            transaction_id: string
            status: components["schemas"]["CheckoutResponseStatusEnum"]
            /** Format: uri */
            payment_url: string | null
            /** Format: date-time */
            expires_at: string | null
        }
        /**
         * @description * `PENDING_PAYMENT` - PENDING_PAYMENT
         *     * `CONFIRMED` - CONFIRMED
         * @enum {string}
         */
        CheckoutResponseStatusEnum: "PENDING_PAYMENT" | "CONFIRMED"
        CheckoutSubscriptionRequest: {
            plan_id: number
            student_id: number
            /** @default false */
            use_deposit: boolean
            slot_ids: number[]
        }
        CheckoutTrialRequest: {
            student_id: number
            schedule_id: number
            /** Format: date */
            trial_date: string
        }
        Child: {
            readonly id: number
            /** ФИО */
            full_name: string
            /**
             * Дата рождения
             * Format: date
             */
            dob: string
            /** Класс */
            school_grade?: string
            /** Особенности здоровья */
            health_issues?: string
        }
        ChildRequest: {
            /** ФИО */
            full_name: string
            /**
             * Дата рождения
             * Format: date
             */
            dob: string
            /** Класс */
            school_grade?: string
            /** Особенности здоровья */
            health_issues?: string
        }
        DepositBalance: {
            readonly balance: number
        }
        DepositEntryView: {
            readonly id: number
            readonly amount: number
            readonly reason: components["schemas"]["ReasonEnum"]
            readonly reason_display: string
            readonly subscription_id: number | null
            readonly subscription_display_id: string | null
            /** Format: date-time */
            readonly created_at: string
        }
        EventPublic: {
            readonly id: number
            /** Название */
            title: string
            /** Описание */
            description?: string
            /** Обложка (URL) */
            cover_image?: string
            /**
             * Начало
             * Format: date-time
             */
            start_datetime: string
            /** Длительность, мин */
            duration_minutes?: number
            /** Цена */
            price?: number
            readonly is_free: boolean
            /** Вместимость */
            capacity: number
            readonly is_upcoming: boolean
        }
        EventRegistrationCreateRequest: {
            /** Имя ребёнка */
            child_name: string
            /** Имя родителя */
            parent_name: string
            /** Телефон */
            phone: string
            email?: string
            /** @default 1 */
            attendees_count: number
            /** Откуда узнали */
            source?: string
            /** Комментарий */
            comment?: string
            /** @description Согласие на обработку персональных данных. Обязательно true; галочка на фронте не должна стоять по умолчанию */
            pd_consent: boolean
            /** @default  */
            website_url: string
        }
        FeedbackRequestCreateRequest: {
            /** Имя */
            name?: string
            /** Format: email */
            email: string
            /** Сообщение */
            message: string
            /** @description Согласие на обработку персональных данных. Обязательно true; галочка на фронте не должна стоять по умолчанию */
            pd_consent: boolean
            /** @default  */
            website_url: string
            /** @default  */
            captcha_token: string
        }
        GalleryImagePublic: {
            readonly id: number
            /**
             * Изображение (URL)
             * Format: uri
             */
            image_url: string
            /** Порядок */
            order?: number
        }
        /**
         * @description * `TRIAL` - Пробное занятие
         *     * `EVENT` - Событие
         * @enum {string}
         */
        KindEnum: "TRIAL" | "EVENT"
        LogoutRequest: {
            /** @description Refresh-токен для аннулирования */
            refresh: string
        }
        OTPRequestRequest: {
            /**
             * Format: email
             * @description Email адрес для получения кода
             */
            email: string
        }
        OTPVerifyRequest: {
            /**
             * Format: email
             * @description Email адрес, на который был отправлен код
             */
            email: string
            /** @description Шестизначный числовой код из письма */
            code: string
        }
        OTPVerifyResponse: {
            access: string
            refresh: string
            /** @description false — показать анкету (PATCH /me/profile/); до её заполнения ЛК и покупки отвечают 403 */
            profile_completed: boolean
        }
        OverrideNested: {
            readonly original_start_time: string
            readonly reason: string
        }
        PaginatedGalleryImagePublicList: {
            /** @example 123 */
            count: number
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null
            results: components["schemas"]["GalleryImagePublic"][]
        }
        PatchedChildRequest: {
            /** ФИО */
            full_name?: string
            /**
             * Дата рождения
             * Format: date
             */
            dob?: string
            /** Класс */
            school_grade?: string
            /** Особенности здоровья */
            health_issues?: string
        }
        PatchedProfileRequest: {
            /** ФИО */
            full_name?: string
            /** Телефон */
            phone?: string
            /**
             * @description Откуда узнали о центре. В ответе у старых родителей бывает UNKNOWN
             *
             *     * `FRIENDS` - Друзья, знакомые
             *     * `SOCIAL` - Соцсети (VK, Telegram)
             *     * `MAPS` - Яндекс.Карты, 2ГИС
             *     * `SEARCH` - Поиск в интернете
             *     * `SIGN` - Вывеска, проходил мимо
             *     * `SCHOOL` - Школа, детский сад
             *     * `OTHER` - Другое
             */
            referral_source?: components["schemas"]["ReferralSourceEnum"]
            /** @description Согласие на обработку персональных данных. Обязательно true; галочка на фронте не должна стоять по умолчанию */
            pd_consent?: boolean
        }
        /**
         * @description * `MORNING` - Утро (9:00–12:00)
         *     * `AFTERNOON` - День (12:00–17:00)
         *     * `EVENING` - Вечер (17:00–21:00)
         * @enum {string}
         */
        PreferredTimeWindowEnum: "MORNING" | "AFTERNOON" | "EVENING"
        Profile: {
            readonly id: number
            /** ФИО */
            full_name?: string
            /** Телефон */
            phone?: string
            /** Format: email */
            readonly email: string
            /**
             * @description Откуда узнали о центре. В ответе у старых родителей бывает UNKNOWN
             *
             *     * `FRIENDS` - Друзья, знакомые
             *     * `SOCIAL` - Соцсети (VK, Telegram)
             *     * `MAPS` - Яндекс.Карты, 2ГИС
             *     * `SEARCH` - Поиск в интернете
             *     * `SIGN` - Вывеска, проходил мимо
             *     * `SCHOOL` - Школа, детский сад
             *     * `OTHER` - Другое
             */
            referral_source: components["schemas"]["ReferralSourceEnum"]
            /**
             * Format: date-time
             * @description Когда дано согласие на обработку ПД; null — галочку надо показать
             */
            readonly pd_consent_at: string
            /** @description false — показать анкету; ЛК и покупки до её заполнения закрыты */
            readonly profile_completed: boolean
            readonly children: components["schemas"]["Child"][]
        }
        /**
         * @description * `SUBSCRIPTION_EXPIRY_CREDIT` - Несгораемый остаток абонемента
         *     * `CHECKOUT_SPEND` - Списание при покупке
         *     * `ORDER_CANCELED_RETURN` - Возврат за неисполненный заказ
         * @enum {string}
         */
        ReasonEnum: "SUBSCRIPTION_EXPIRY_CREDIT" | "CHECKOUT_SPEND" | "ORDER_CANCELED_RETURN"
        /**
         * @description * `FRIENDS` - Друзья, знакомые
         *     * `SOCIAL` - Соцсети (VK, Telegram)
         *     * `MAPS` - Яндекс.Карты, 2ГИС
         *     * `SEARCH` - Поиск в интернете
         *     * `SIGN` - Вывеска, проходил мимо
         *     * `SCHOOL` - Школа, детский сад
         *     * `OTHER` - Другое
         * @enum {string}
         */
        ReferralSourceEnum: "FRIENDS" | "SOCIAL" | "MAPS" | "SEARCH" | "SIGN" | "SCHOOL" | "OTHER"
        RegistrationAccepted: {
            status: string
        }
        RoomNested: {
            readonly id: number
            readonly name: string
        }
        ScheduleGroupPublic: {
            readonly id: number
            /** Название группы */
            group_name?: string
            /** Возраст от */
            age_min?: number | null
            /** Возраст до */
            age_max?: number | null
            /** Максимум детей */
            max_capacity?: number
        }
        SubmissionAccepted: {
            status: string
        }
        SubscriptionPlanPublic: {
            readonly id: number
            /** Название */
            name: string
            /** Число слотов */
            slots_count: number
            /** Цена, в копейках */
            price: number
            readonly price_per_session: number
            /** Безлимит */
            is_unlimited?: boolean
        }
        SubscriptionSlotView: {
            readonly schedule_id: number
            readonly activity_name: string
            readonly group_name: string
            readonly schedule: string
            readonly remaining_sessions: number
            readonly total_sessions: number
        }
        SubscriptionView: {
            readonly id: number
            readonly display_id: string
            readonly status: components["schemas"]["SubscriptionViewStatusEnum"]
            readonly student_name: string
            readonly purchase_price: number
            /** Format: date-time */
            readonly created_at: string
            /** Format: date */
            readonly start_date: string | null
            /** Format: date-time */
            readonly expires_at: string | null
            readonly total_remaining: number
            readonly slots: components["schemas"]["SubscriptionSlotView"][]
        }
        /**
         * @description * `ACTIVE` - Активен
         *     * `EXPIRED` - Истёк
         * @enum {string}
         */
        SubscriptionViewStatusEnum: "ACTIVE" | "EXPIRED"
        TeacherActivityNested: {
            readonly id: number
            readonly name: string
            readonly slug: string
        }
        TeacherNested: {
            readonly id: number
            readonly full_name: string
        }
        TeacherPublic: {
            readonly id: number
            readonly full_name: string
            /** Отчество */
            middle_name?: string
            /** Фото (URL) */
            photo_url?: string
            /** Должность на витрине */
            position?: string
            /** Цитата */
            quote?: string
            /** О преподавателе */
            bio?: string
            readonly activities: components["schemas"]["TeacherActivityNested"][]
        }
        TokenRefreshRequest: {
            refresh: string
        }
        TokenRefreshResponse: {
            access: string
            refresh: string
        }
        TrialSlot: {
            readonly schedule_id: number
            /** Format: date */
            readonly date: string
            /** Format: time */
            readonly start_time: string
            /** Format: time */
            readonly end_time: string
            readonly group_name: string
            readonly teacher: components["schemas"]["TeacherNested"] | null
            readonly is_rescheduled: boolean
        }
        TrialSlotsActivity: {
            readonly id: number
            readonly name: string
        }
        TrialSlotsResponse: {
            readonly activity: components["schemas"]["TrialSlotsActivity"]
            /** Format: date */
            readonly date_from: string
            /** Format: date */
            readonly date_to: string
            readonly slots: components["schemas"]["TrialSlot"][]
        }
        TrialView: {
            readonly id: number
            readonly student_id: number
            readonly student_name: string
            readonly activity_name: string
            readonly group_name: string
            /** Format: date */
            readonly trial_date: string
            /** Format: time */
            readonly start_time: string
            /** Format: time */
            readonly end_time: string
            readonly status: string
            readonly cost: number | null
            /** Format: date-time */
            readonly created_at: string
        }
        UpcomingItem: {
            readonly kind: string
            readonly date: string
            readonly time: string
            readonly student_id: number | null
            readonly student_name: string | null
            readonly activity_name: string | null
            readonly group_name: string | null
            readonly title: string | null
            readonly source_type: string
            readonly source_id: number
            readonly is_rescheduled: boolean
        }
        WeekGridResponse: {
            /** Format: date */
            readonly week_start: string
            /** Format: date */
            readonly week_end: string
            readonly slots: components["schemas"]["WeekSlot"][]
        }
        WeekSlot: {
            readonly schedule_id: number
            /** Format: date */
            readonly date: string
            readonly day_of_week: number
            /** Format: time */
            readonly start_time: string
            /** Format: time */
            readonly end_time: string
            readonly group_name: string
            readonly activity: components["schemas"]["ActivityNested"]
            readonly teacher: components["schemas"]["TeacherNested"] | null
            readonly room: components["schemas"]["RoomNested"] | null
            readonly capacity: components["schemas"]["CapacityNested"]
            readonly is_rescheduled: boolean
            readonly is_cancelled: boolean
            readonly override: components["schemas"]["OverrideNested"] | null
        }
        YookassaWebhookRequest: {
            event: string
            object: components["schemas"]["_YookassaPaymentObjectRequest"]
        }
        _YookassaPaymentObjectRequest: {
            id: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    v1_auth_logout_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"]
                "multipart/form-data": components["schemas"]["LogoutRequest"]
            }
        }
        responses: {
            /** @description Успешный выход, токен аннулирован */
            205: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Ошибка валидации формата полей */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Невалидный или истёкший токен */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    v1_auth_otp_request_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequestRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["OTPRequestRequest"]
                "multipart/form-data": components["schemas"]["OTPRequestRequest"]
            }
        }
        responses: {
            /** @description Код отправлен на email */
            202: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Ошибка валидации формата email */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Cooldown: повторный запрос слишком рано */
            429: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    v1_auth_otp_verify_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerifyRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["OTPVerifyRequest"]
                "multipart/form-data": components["schemas"]["OTPVerifyRequest"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["OTPVerifyResponse"]
                }
            }
            /** @description Ошибка валидации формата полей */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Неверный или истёкший код */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Превышен лимит попыток */
            429: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"]
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"]
                }
            }
            /** @description Невалидный или истёкший refresh-токен */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    v1_checkout_subscription_create: {
        parameters: {
            query?: never
            header: {
                /** @description UUID v4, новый на каждую покупку. Повтор с тем же ключом и тем же телом вернёт тот же ответ, с другим телом — 409. */
                "X-Idempotency-Key": string
            }
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSubscriptionRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutSubscriptionRequest"]
                "multipart/form-data": components["schemas"]["CheckoutSubscriptionRequest"]
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"]
                }
            }
        }
    }
    v1_checkout_trial_create: {
        parameters: {
            query?: never
            header: {
                /** @description UUID v4, новый на каждую покупку. Повтор с тем же ключом и тем же телом вернёт тот же ответ, с другим телом — 409. */
                "X-Idempotency-Key": string
            }
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutTrialRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutTrialRequest"]
                "multipart/form-data": components["schemas"]["CheckoutTrialRequest"]
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"]
                }
            }
        }
    }
    me_bookings: {
        parameters: {
            query?: {
                /** @description Без параметра — оба вида. */
                kind?: "EVENT" | "TRIAL"
                /** @description Размер страницы, 1..60 (больше — урезается). Без limit — весь список массивом; с limit — конверт {count, next, previous, results}. */
                limit?: number
                /** @description Сколько элементов пропустить, по умолчанию 0. */
                offset?: number
                period?: "all" | "past" | "upcoming"
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Booking"][]
                }
            }
        }
    }
    me_child_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["ChildRequest"]
                "multipart/form-data": components["schemas"]["ChildRequest"]
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Child"]
                }
            }
        }
    }
    me_child_delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Удалён */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Чужой, несуществующий или уже удалённый ребёнок */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description CHILD_HAS_ACTIVE_ENROLLMENTS */
            409: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    me_child_update: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: number
            }
            cookie?: never
        }
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChildRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChildRequest"]
                "multipart/form-data": components["schemas"]["PatchedChildRequest"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Child"]
                }
            }
        }
    }
    me_deposit: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["DepositBalance"]
                }
            }
        }
    }
    me_deposit_entries: {
        parameters: {
            query?: {
                /** @description Размер страницы, 1..60 (больше — урезается). Без limit — весь список массивом; с limit — конверт {count, next, previous, results}. */
                limit?: number
                /** @description Сколько элементов пропустить, по умолчанию 0. */
                offset?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["DepositEntryView"][]
                }
            }
        }
    }
    me_profile: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Profile"]
                }
            }
        }
    }
    me_profile_update: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileRequest"]
                "multipart/form-data": components["schemas"]["PatchedProfileRequest"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Profile"]
                }
            }
        }
    }
    me_subscriptions: {
        parameters: {
            query?: {
                /** @description Размер страницы, 1..60 (больше — урезается). Без limit — весь список массивом; с limit — конверт {count, next, previous, results}. */
                limit?: number
                /** @description Сколько элементов пропустить, по умолчанию 0. */
                offset?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SubscriptionView"][]
                }
            }
        }
    }
    me_trials: {
        parameters: {
            query?: {
                /** @description Размер страницы, 1..60 (больше — урезается). Без limit — весь список массивом; с limit — конверт {count, next, previous, results}. */
                limit?: number
                /** @description Сколько элементов пропустить, по умолчанию 0. */
                offset?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TrialView"][]
                }
            }
        }
    }
    me_upcoming: {
        parameters: {
            query?: {
                child_id?: number
                /** @description Размер страницы, 1..60 (больше — урезается). Без limit — весь список массивом; с limit — конверт {count, next, previous, results}. */
                limit?: number
                /** @description Сколько элементов пропустить, по умолчанию 0. */
                offset?: number
                weeks?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["UpcomingItem"][]
                }
            }
        }
    }
    public_activities_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ActivityDetail"][]
                }
            }
        }
    }
    public_activity_detail: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ActivityDetail"]
                }
            }
        }
    }
    public_activity_next_slots: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TrialSlotsResponse"]
                }
            }
        }
    }
    public_activities_popular: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ActivityCard"][]
                }
            }
        }
    }
    v1_public_callback_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackRequestCreateRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["CallbackRequestCreateRequest"]
                "multipart/form-data": components["schemas"]["CallbackRequestCreateRequest"]
            }
        }
        responses: {
            202: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SubmissionAccepted"]
                }
            }
        }
    }
    public_events_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["EventPublic"][]
                }
            }
        }
    }
    public_event_register: {
        parameters: {
            query?: never
            header?: never
            path: {
                event_id: number
            }
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRegistrationCreateRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["EventRegistrationCreateRequest"]
                "multipart/form-data": components["schemas"]["EventRegistrationCreateRequest"]
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["RegistrationAccepted"]
                }
            }
        }
    }
    v1_public_feedback_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequestCreateRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequestCreateRequest"]
                "multipart/form-data": components["schemas"]["FeedbackRequestCreateRequest"]
            }
        }
        responses: {
            202: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SubmissionAccepted"]
                }
            }
        }
    }
    public_gallery_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number
                /** @description The initial index from which to return the results. */
                offset?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["PaginatedGalleryImagePublicList"]
                }
            }
        }
    }
    public_plans_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SubscriptionPlanPublic"][]
                }
            }
        }
    }
    public_schedule_week: {
        parameters: {
            query?: {
                /** @description Понедельник запрашиваемой недели (ISO 8601, YYYY-MM-DD). По умолчанию — текущая неделя; не-понедельник нормализуется к началу своей недели. */
                week_start?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["WeekGridResponse"]
                }
            }
        }
    }
    public_teachers_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TeacherPublic"][]
                }
            }
        }
    }
    v1_webhooks_yookassa_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["YookassaWebhookRequest"]
                "application/x-www-form-urlencoded": components["schemas"]["YookassaWebhookRequest"]
                "multipart/form-data": components["schemas"]["YookassaWebhookRequest"]
            }
        }
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
