/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/otp/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запрос OTP-кода */
        post: operations["v1_auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Верификация OTP-кода */
        post: operations["v1_auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Идемпотентное создание платежа за абонемент. Заголовок X-Idempotency-Key (UUID v4) обязателен. Родитель определяется по сессии — parent_id в теле не принимается. */
        post: operations["v1_checkout_subscription_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/children/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить ребёнка */
        post: operations["me_child_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/children/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить данные ребёнка */
        patch: operations["me_child_update"];
        trace?: never;
    };
    "/api/v1/me/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль родителя с детьми */
        get: operations["me_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Профиль родителя с детьми */
        patch: operations["me_profile_2"];
        trace?: never;
    };
    "/api/v1/me/subscriptions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои абонементы с балансом по слотам */
        get: operations["me_subscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/upcoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Лента ближайших активностей (занятия + события) */
        get: operations["me_upcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полный каталог кружков («Все кружки») */
        get: operations["public_activities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/activities/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Детальная карточка кружка с подгруппами */
        get: operations["public_activity_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/activities/popular/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Топ-3 популярных кружка */
        get: operations["public_activities_popular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/callback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Заказ обратного звонка */
        post: operations["v1_public_callback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Афиша: будущие события и прошедшие за 7 дней */
        get: operations["public_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{event_id}/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Гостевая регистрация на событие */
        post: operations["public_event_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обратная связь */
        post: operations["v1_public_feedback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/gallery/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опубликованные фото галереи */
        get: operations["public_gallery_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Тарифные планы абонементов */
        get: operations["public_plans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Недельная сетка расписания */
        get: operations["public_schedule_week"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/teachers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Преподаватели с их кружками */
        get: operations["public_teachers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/yookassa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Вебхук ЮКассы. Быстро ставит верификацию платежа в очередь. */
        post: operations["v1_webhooks_yookassa_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityCard: {
            readonly id: number;
            /** Название */
            name: string;
            /** Слуг */
            slug: string;
            /** Категория */
            category?: string;
            /** Цена */
            price?: number;
            /** Обложка (URL) */
            cover_image?: string;
            /** Краткое описание */
            short_description?: string;
            /** Особенности */
            features?: unknown;
            /** Теги */
            tags?: unknown;
        };
        ActivityDetail: {
            readonly id: number;
            /** Название */
            name: string;
            /** Слуг */
            slug: string;
            /** Категория */
            category?: string;
            /** Цена */
            price?: number;
            /** Обложка (URL) */
            cover_image?: string;
            /** Краткое описание */
            short_description?: string;
            /** Особенности */
            features?: unknown;
            /** Теги */
            tags?: unknown;
            /** Описание */
            description?: string;
            readonly groups: components["schemas"]["ScheduleGroupPublic"][];
            readonly teachers: components["schemas"]["ActivityTeacherNested"][];
            readonly days_of_week: number[];
        };
        ActivityNested: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
        };
        ActivityTeacherNested: {
            readonly id: number;
            readonly full_name: string;
            readonly photo_url: string;
            readonly position: string;
        };
        CallbackRequestCreateRequest: {
            /** Имя */
            name: string;
            /** Телефон */
            phone: string;
            /** Удобное время звонка */
            preferred_time_window: components["schemas"]["PreferredTimeWindowEnum"];
            /** @default  */
            website_url: string;
            /** @default  */
            captcha_token: string;
        };
        CapacityNested: {
            readonly max: number;
            readonly taken: number;
            readonly free: number;
        };
        CheckoutResponse: {
            /** Format: uuid */
            transaction_id: string;
            status: components["schemas"]["StatusEnum"];
            /** Format: uri */
            payment_url: string | null;
            /** Format: date-time */
            expires_at: string | null;
        };
        CheckoutSubscriptionRequest: {
            plan_id: number;
            student_id: number;
            /** @default false */
            use_deposit: boolean;
            slot_ids: number[];
        };
        Child: {
            readonly id: number;
            /** ФИО */
            full_name: string;
            /**
             * Дата рождения
             * Format: date
             */
            dob: string;
            /** Класс */
            school_grade?: string;
            /** Особенности здоровья */
            health_issues?: string;
        };
        ChildRequest: {
            /** ФИО */
            full_name: string;
            /**
             * Дата рождения
             * Format: date
             */
            dob: string;
            /** Класс */
            school_grade?: string;
            /** Особенности здоровья */
            health_issues?: string;
        };
        EventPublic: {
            readonly id: number;
            /** Название */
            title: string;
            /** Описание */
            description?: string;
            /** Обложка (URL) */
            cover_image?: string;
            /**
             * Начало
             * Format: date-time
             */
            start_datetime: string;
            /** Длительность, мин */
            duration_minutes?: number;
            /** Цена */
            price?: number;
            readonly is_free: boolean;
            /** Вместимость */
            capacity: number;
            readonly is_upcoming: boolean;
        };
        EventRegistrationCreateRequest: {
            /** Имя ребёнка */
            child_name: string;
            /** Имя родителя */
            parent_name: string;
            /** Телефон */
            phone: string;
            email?: string;
            /** @default 1 */
            attendees_count: number;
            /** Откуда узнали */
            source?: string;
            /** Комментарий */
            comment?: string;
            /** @default  */
            website_url: string;
        };
        FeedbackRequestCreateRequest: {
            /** Имя */
            name?: string;
            /** Format: email */
            email: string;
            /** Сообщение */
            message: string;
            /** @default  */
            website_url: string;
            /** @default  */
            captcha_token: string;
        };
        GalleryImagePublic: {
            readonly id: number;
            /**
             * Изображение (URL)
             * Format: uri
             */
            image_url: string;
            /** Порядок */
            order?: number;
        };
        OTPRequestRequest: {
            /**
             * Format: email
             * @description Email адрес для получения кода
             */
            email: string;
        };
        OTPVerifyRequest: {
            /**
             * Format: email
             * @description Email адрес, на который был отправлен код
             */
            email: string;
            /** @description Шестизначный числовой код из письма */
            code: string;
        };
        OverrideNested: {
            readonly original_start_time: string;
            readonly reason: string;
        };
        PatchedChildRequest: {
            /** ФИО */
            full_name?: string;
            /**
             * Дата рождения
             * Format: date
             */
            dob?: string;
            /** Класс */
            school_grade?: string;
            /** Особенности здоровья */
            health_issues?: string;
        };
        PatchedProfileRequest: {
            /** ФИО */
            full_name?: string;
            /** Телефон */
            phone?: string;
        };
        /**
         * @description * `MORNING` - Утро (9:00–12:00)
         *     * `AFTERNOON` - День (12:00–17:00)
         *     * `EVENING` - Вечер (17:00–21:00)
         * @enum {string}
         */
        PreferredTimeWindowEnum: "MORNING" | "AFTERNOON" | "EVENING";
        Profile: {
            readonly id: number;
            /** ФИО */
            full_name?: string;
            /** Телефон */
            phone?: string;
            /** Format: email */
            readonly email: string;
            readonly children: components["schemas"]["Child"][];
        };
        RegistrationAccepted: {
            status: string;
        };
        RoomNested: {
            readonly id: number;
            readonly name: string;
        };
        ScheduleGroupPublic: {
            readonly id: number;
            /** Название группы */
            group_name?: string;
            /** Возраст от */
            age_min?: number | null;
            /** Возраст до */
            age_max?: number | null;
            /** День недели (денорм.) */
            readonly day_of_week: number;
            readonly day_of_week_display: string;
            /** Format: time */
            readonly start_time: string;
            /** Format: time */
            readonly end_time: string;
            /** Максимум детей */
            max_capacity?: number;
            readonly seats_free: number;
        };
        /**
         * @description * `PENDING_PAYMENT` - PENDING_PAYMENT
         *     * `CONFIRMED` - CONFIRMED
         * @enum {string}
         */
        StatusEnum: "PENDING_PAYMENT" | "CONFIRMED";
        SubmissionAccepted: {
            status: string;
        };
        SubscriptionPlanPublic: {
            readonly id: number;
            /** Название */
            name: string;
            /** Число слотов */
            slots_count: number;
            /** Цена, в копейках */
            price: number;
            readonly price_per_session: number;
            /** Безлимит */
            is_unlimited?: boolean;
        };
        SubscriptionSlotView: {
            readonly schedule_id: number;
            readonly activity_name: string;
            readonly group_name: string;
            readonly day_of_week: number;
            /** Format: time */
            readonly start_time: string;
            /** Format: time */
            readonly end_time: string;
            readonly student_id: number;
            readonly student_name: string;
            readonly remaining_sessions: number;
        };
        SubscriptionView: {
            readonly id: number;
            readonly display_id: string;
            readonly status: string;
            readonly student_name: string;
            readonly purchase_price: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date */
            readonly start_date: string | null;
            /** Format: date-time */
            readonly expires_at: string | null;
            readonly slots: components["schemas"]["SubscriptionSlotView"][];
        };
        TeacherActivityNested: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
        };
        TeacherNested: {
            readonly id: number;
            readonly full_name: string;
        };
        TeacherPublic: {
            readonly id: number;
            readonly full_name: string;
            /** Отчество */
            middle_name?: string;
            /** Фото (URL) */
            photo_url?: string;
            /** Должность на витрине */
            position?: string;
            /** Цитата */
            quote?: string;
            /** О преподавателе */
            bio?: string;
            readonly activities: components["schemas"]["TeacherActivityNested"][];
        };
        UpcomingItem: {
            readonly kind: string;
            /** Format: date */
            readonly date: string;
            /** Format: time */
            readonly start_time: string;
            /** Format: time */
            readonly end_time: string | null;
            readonly student_id: number | null;
            readonly student_name: string | null;
            readonly activity_name: string | null;
            readonly group_name: string | null;
            readonly title: string | null;
            readonly source_type: string;
            readonly source_id: number;
            readonly is_rescheduled: boolean;
        };
        WeekGridResponse: {
            /** Format: date */
            readonly week_start: string;
            /** Format: date */
            readonly week_end: string;
            readonly slots: components["schemas"]["WeekSlot"][];
        };
        WeekSlot: {
            readonly schedule_id: number;
            /** Format: date */
            readonly date: string;
            readonly day_of_week: number;
            /** Format: time */
            readonly start_time: string;
            /** Format: time */
            readonly end_time: string;
            readonly activity: components["schemas"]["ActivityNested"];
            readonly teacher: components["schemas"]["TeacherNested"] | null;
            readonly room: components["schemas"]["RoomNested"] | null;
            readonly capacity: components["schemas"]["CapacityNested"];
            readonly is_rescheduled: boolean;
            readonly is_cancelled: boolean;
            readonly override: components["schemas"]["OverrideNested"] | null;
        };
        YookassaWebhookRequest: {
            event: string;
            object: components["schemas"]["_YookassaPaymentObjectRequest"];
        };
        _YookassaPaymentObjectRequest: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OTPRequestRequest"];
                "multipart/form-data": components["schemas"]["OTPRequestRequest"];
            };
        };
        responses: {
            /** @description Код отправлен на email */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации формата email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cooldown: повторный запрос слишком рано */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OTPVerifyRequest"];
                "multipart/form-data": components["schemas"]["OTPVerifyRequest"];
            };
        };
        responses: {
            /** @description Токены выданы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации формата полей */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неверный или истёкший код */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Превышен лимит попыток */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_checkout_subscription_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSubscriptionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutSubscriptionRequest"];
                "multipart/form-data": components["schemas"]["CheckoutSubscriptionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
        };
    };
    me_child_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChildRequest"];
                "multipart/form-data": components["schemas"]["ChildRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Child"];
                };
            };
        };
    };
    me_child_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChildRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChildRequest"];
                "multipart/form-data": components["schemas"]["PatchedChildRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Child"];
                };
            };
        };
    };
    me_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_subscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionView"][];
                };
            };
        };
    };
    me_upcoming: {
        parameters: {
            query?: {
                child_id?: number;
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingItem"][];
                };
            };
        };
    };
    public_activities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"][];
                };
            };
        };
    };
    public_activity_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
        };
    };
    public_activities_popular: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityCard"][];
                };
            };
        };
    };
    v1_public_callback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackRequestCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CallbackRequestCreateRequest"];
                "multipart/form-data": components["schemas"]["CallbackRequestCreateRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionAccepted"];
                };
            };
        };
    };
    public_events_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPublic"][];
                };
            };
        };
    };
    public_event_register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRegistrationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRegistrationCreateRequest"];
                "multipart/form-data": components["schemas"]["EventRegistrationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationAccepted"];
                };
            };
        };
    };
    v1_public_feedback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequestCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequestCreateRequest"];
                "multipart/form-data": components["schemas"]["FeedbackRequestCreateRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionAccepted"];
                };
            };
        };
    };
    public_gallery_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryImagePublic"][];
                };
            };
        };
    };
    public_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlanPublic"][];
                };
            };
        };
    };
    public_schedule_week: {
        parameters: {
            query?: {
                /** @description Понедельник запрашиваемой недели (ISO 8601, YYYY-MM-DD). По умолчанию — текущая неделя; не-понедельник нормализуется к началу своей недели. */
                week_start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekGridResponse"];
                };
            };
        };
    };
    public_teachers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherPublic"][];
                };
            };
        };
    };
    v1_webhooks_yookassa_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YookassaWebhookRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["YookassaWebhookRequest"];
                "multipart/form-data": components["schemas"]["YookassaWebhookRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
